/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2018-12-21 02:53:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <base href=\"");
      out.print(basePath);
      out.write("\"> \r\n");
      out.write("  <title>校园宿舍管理系统</title>\r\n");
      out.write("  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("  <link href=\"Style/Style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<script language=\"JavaScript\">\r\n");
      out.write("\r\n");
      out.write("function mycheck(){\r\n");
      out.write("   if(isNull(form1.Type.value)){  \r\n");
      out.write("   alert(\"请选择身份！\"); \r\n");
      out.write("   return false;\r\n");
      out.write("   }\r\n");
      out.write("   if(isNull(form1.Username.value)){  \r\n");
      out.write("   alert(\"请输入用户名！\"); \r\n");
      out.write("   return false;\r\n");
      out.write("   }\r\n");
      out.write("   if(isNull(form1.Password.value)){\r\n");
      out.write("   alert(\"请输入密码！\");\r\n");
      out.write("   return false;\r\n");
      out.write("   }\r\n");
      out.write("      \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function isNull(str){\r\n");
      out.write("if ( str == \"\" ) return true;\r\n");
      out.write("var regu = \"^[ ]+$\";\r\n");
      out.write("var re = new RegExp(regu);\r\n");
      out.write("return re.test(str);\r\n");
      out.write("}\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("<center>\r\n");
      out.write("  <br><br><br><br><br>\r\n");
      out.write("  <table width=\"684\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td height=\"292\" align=\"center\" valign=\"top\" background=\"Images/LoginBg.jpg\">\r\n");
      out.write("      <table width=\"350\" height=\"201\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td height=\"72\" align=\"center\"><h3>校园宿舍管理系统</h3></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td align=\"center\" valign=\"top\">\r\n");
      out.write("             <form name=\"form1\" action=\"GoLogin.action\" method=\"post\" onSubmit=\"return mycheck()\">\r\n");
      out.write("              <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <td height=\"30\" colspan=\"2\" align=\"center\" class=\"STYLE2\"><span style=\"color:red;\">\r\n");
      out.write("                    ");
if(request.getAttribute("Msg")!=null){
      out.write("\r\n");
      out.write("                    ");
      out.print(request.getAttribute("Msg"));
      out.write("\r\n");
      out.write("                    ");
}
      out.write("\r\n");
      out.write("                  </span></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <td height=\"30\" align=\"right\" class=\"STYLE2\">身份：</td>\r\n");
      out.write("                  <td align=\"left\"><select name=\"Type\" id=\"Type\">\r\n");
      out.write("                    <option value=\"\">请选择</option>\r\n");
      out.write("                    <option value=\"系统管理员\">系统管理员</option>\r\n");
      out.write("                    <option value=\"楼宇管理员\">楼宇管理员</option>\r\n");
      out.write("                    <option value=\"学生\">学生</option>\r\n");
      out.write("                  </select></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <td width=\"37%\" height=\"30\" align=\"right\" class=\"STYLE2\">用户名：</td>\r\n");
      out.write("                  <td width=\"300\" align=\"left\"><input type=\"text\" name=\"Username\" id=\"Username\" class=\"text1\" /></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <td height=\"30\" align=\"right\" class=\"STYLE2\">密码：</td>\r\n");
      out.write("                  <td align=\"left\"><input type=\"password\" name=\"Password\" id=\"Password\" class=\"text1\" /></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <td height=\"30\" colspan=\"2\" align=\"center\"><label>\r\n");
      out.write("                    <input type=\"submit\" name=\"button\" id=\"button\" value=\"登录\">\r\n");
      out.write("                  </label></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("              </table>\r\n");
      out.write("              </form>\r\n");
      out.write("          \r\n");
      out.write("          </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("      </table></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("  </table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
