/*
    *
    * Wijmo Library 5.20183.550
    * http://wijmo.com/
    *
    * Copyright(c) GrapeCity, Inc.  All rights reserved.
    *
    * Licensed under the GrapeCity Commercial License.
    * sales@wijmo.com
    * wijmo.com/products/wijmo-5/license/
    *
    */
import*as wjcReactBase from"wijmo/wijmo.react.base";import*as wjcInput from"wijmo/wijmo.input";var __glob="undefined"!=typeof window?window:self;import*as wjcSelfRef from"wijmo/wijmo.react.input";var wjcSelf=wjcSelfRef||exports;__glob.wijmo=__glob.wijmo||{},__glob.wijmo.react=__glob.wijmo.react||{},__glob.wijmo.react.input=wjcSelf;import*as React from"react";export class ListBox extends wjcReactBase.ComponentBase{constructor(e){super(e,wjcInput.ListBox,{objectProps:["itemsSource","selectedItem","selectedValue","checkedItems"]})}};export class ComboBox extends wjcReactBase.ComponentBase{constructor(e){super(e,wjcInput.ComboBox,{objectProps:["itemsSource","selectedItem","selectedValue"]})}};export class AutoComplete extends wjcReactBase.ComponentBase{constructor(e){super(e,wjcInput.AutoComplete,{objectProps:["itemsSource","selectedItem","selectedValue"]})}};export class Calendar extends wjcReactBase.ComponentBase{constructor(e){super(e,wjcInput.Calendar)}};export class ColorPicker extends wjcReactBase.ComponentBase{constructor(e){super(e,wjcInput.ColorPicker,{objectProps:["palette"]})}};export class InputMask extends wjcReactBase.ComponentBase{constructor(e){super(e,wjcInput.InputMask)}};export class InputColor extends wjcReactBase.ComponentBase{constructor(e){super(e,wjcInput.InputColor)}};export class MultiSelect extends wjcReactBase.ComponentBase{constructor(e){super(e,wjcInput.MultiSelect,{objectProps:["itemsSource","selectedItem","selectedValue","checkedItems"]})}};export class MultiAutoComplete extends wjcReactBase.ComponentBase{constructor(e){super(e,wjcInput.MultiAutoComplete,{objectProps:["itemsSource","selectedItem","selectedValue","selectedItems"]})}};export class InputNumber extends wjcReactBase.ComponentBase{constructor(e){super(e,wjcInput.InputNumber)}};export class InputDate extends wjcReactBase.ComponentBase{constructor(e){super(e,wjcInput.InputDate)}};export class InputTime extends wjcReactBase.ComponentBase{constructor(e){super(e,wjcInput.InputTime,{objectProps:["itemsSource","selectedItem","selectedValue"]})}};export class InputDateTime extends wjcReactBase.ComponentBase{constructor(e){super(e,wjcInput.InputDateTime)}};export class Menu extends wjcReactBase.ComponentBase{constructor(e){super(e,wjcInput.Menu,{objectProps:["itemsSource","selectedItem","selectedValue","value"]})}};export class Popup extends wjcReactBase.ComponentBase{constructor(e){super(e,wjcInput.Popup)}render(){return React.createElement("div",null,this.props.children)}};var Wj=wjcReactBase;