/*
    *
    * Wijmo Library 5.20183.550
    * http://wijmo.com/
    *
    * Copyright(c) GrapeCity, Inc.  All rights reserved.
    *
    * Licensed under the GrapeCity Commercial License.
    * sales@wijmo.com
    * wijmo.com/products/wijmo-5/license/
    *
    */
var __extends=this&&this.__extends||function(){var t=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(t,e){t.__proto__=e}||function(t,e){for(var r in e)e.hasOwnProperty(r)&&(t[r]=e[r])};return function(e,r){function n(){this.constructor=e}t(e,r),e.prototype=null===r?Object.create(r):(n.prototype=r.prototype,new n)}}();define(["require","exports","wijmo/wijmo.react.base","wijmo/wijmo.chart","wijmo/wijmo.react.chart"],function(t,e,r,n,o){"use strict";Object.defineProperty(e,"__esModule",{value:!0});var a="undefined"!=typeof window?window:self,i=o||e;a.wijmo=a.wijmo||{},a.wijmo.react=a.wijmo.react||{},a.wijmo.react.chart=i;var s=function(t){function e(e){return t.call(this,e,n.FlexChart,{objectProps:["palette","plotMargin","footerStyle","headerStyle","itemsSource","options","selection"]})||this}return __extends(e,t),e}(r.ComponentBase);e.FlexChart=s;var c=function(t){function e(e){return t.call(this,e,n.FlexPie,{objectProps:["palette","plotMargin","footerStyle","headerStyle","itemsSource"]})||this}return __extends(e,t),e}(r.ComponentBase);e.FlexPie=c;var l=function(t){function e(e){var r=t.call(this,e,n.Axis,{objectProps:["plotArea","itemsSource"]})||this;return r._parentProp="axes",r}return __extends(e,t),e}(r.ComponentBase);e.FlexChartAxis=l;var u=function(t){function e(e){var r=t.call(this,e,n.Legend)||this;return r._parentProp="legend",r._parentInCtor=!0,r}return __extends(e,t),e}(r.ComponentBase);e.FlexChartLegend=u;var p=function(t){function e(e){var r=t.call(this,e,n.DataLabel,{objectProps:["content"]})||this;return r._parentProp="dataLabel",r}return __extends(e,t),e}(r.ComponentBase);e.FlexChartDataLabel=p;var _=function(t){function e(e){var r=t.call(this,e,n.PieDataLabel,{objectProps:["content"]})||this;return r._parentProp="dataLabel",r}return __extends(e,t),e}(r.ComponentBase);e.FlexPieDataLabel=_;var h=function(t){function e(e){var r=t.call(this,e,n.Series,{objectProps:["axisX","axisY","style","altStyle","symbolStyle","itemsSource"]})||this;return r._parentProp="series",r._siblingId="series",r}return __extends(e,t),e}(r.ComponentBase);e.FlexChartSeries=h;var f=function(t){function e(e){var r=t.call(this,e,n.LineMarker)||this;return r._parentInCtor=!0,r}return __extends(e,t),e}(r.ComponentBase);e.FlexChartLineMarker=f;var x=function(t){function e(e){var r=t.call(this,e,n.DataPoint)||this;return r._parentProp="",r}return __extends(e,t),e}(r.ComponentBase);e.FlexChartDataPoint=x;var d=function(t){function e(e){var r=t.call(this,e,n.PlotArea,{objectProps:["style"]})||this;return r._parentProp="plotAreas",r}return __extends(e,t),e}(r.ComponentBase);e.FlexChartPlotArea=d});