/*
    *
    * Wijmo Library 5.20183.550
    * http://wijmo.com/
    *
    * Copyright(c) GrapeCity, Inc.  All rights reserved.
    *
    * Licensed under the GrapeCity Commercial License.
    * sales@wijmo.com
    * wijmo.com/products/wijmo-5/license/
    *
    */
import*as wjcWebcomponentsBase from"wijmo/wijmo.webcomponents.base";import*as wjcGridSheet from"wijmo/wijmo.grid.sheet";var __glob="undefined"!=typeof window?window:self;import*as wjcSelfRef from"wijmo/wijmo.webcomponents.grid.sheet";var wjcSelf=wjcSelfRef||exports;__glob.wijmo=__glob.wijmo||{},__glob.wijmo.webcomponents=__glob.wijmo.webcomponents||{},__glob.wijmo.webcomponents.grid=__glob.wijmo.webcomponents.grid||{},__glob.wijmo.webcomponents.grid.sheet=wjcSelf;let _wj_ns_exists_13=!0;export class WjcFlexSheet extends wjcGridSheet.FlexSheet{constructor(){super(document.createElement("div")),this._wjBehaviour=wjcWebcomponentsBase.WjComponentBehavior._attach(this)}static get observedAttributes(){return wjcWebcomponentsBase.WjComponentBehavior.getProps(this)}connectedCallback(){this._wjBehaviour.lhConnected()}attributeChangedCallback(e,t,o){this._wjBehaviour.lhAttributeChanged(e,t,o)}disconnectedCallback(){this._wjBehaviour.lhDisconnected()}addEventListener(...e){"string"==typeof e[0]?HTMLElement.prototype.addEventListener.apply(this,e):super.addEventListener.apply(this,e)}};_wj_ns_exists_13&&(wjcWebcomponentsBase.WjComponentBehavior.register("",wjcGridSheet._TabHolder),wjcWebcomponentsBase.WjComponentBehavior.register("",wjcGridSheet._ContextMenu),wjcWebcomponentsBase.WjComponentBehavior.register("",wjcGridSheet.FlexSheetColumnFilterEditor),wjcWebcomponentsBase.WjComponentBehavior.register("",wjcGridSheet.FlexSheetValueFilterEditor),wjcWebcomponentsBase.WjComponentBehavior.register("",wjcGridSheet._SheetTabs),wjcWebcomponentsBase.WjComponentBehavior.register("wjc-flex-sheet",WjcFlexSheet));export class WjcSheet extends HTMLElement{constructor(){super(),this._wjBehaviour=wjcWebcomponentsBase.WjComponentBehavior._attach(this)}static get observedAttributes(){return wjcWebcomponentsBase.WjComponentBehavior.getProps(this)}connectedCallback(){this._wjBehaviour.lhConnected()}attributeChangedCallback(e,t,o){this._wjBehaviour.lhAttributeChanged(e,t,o)}disconnectedCallback(){this._wjBehaviour.lhDisconnected()}};WjcSheet.wrappedClass=(()=>wjcGridSheet.Sheet),WjcSheet.parentProp="sheets",_wj_ns_exists_13&&wjcWebcomponentsBase.WjComponentBehavior.register("wjc-sheet",WjcSheet);